#!/usr/bin/env python3

# vigit - Minimal TUI application for working with Git directly from the terminal.
# Copyright (C) 2026 vigit Pavel Shiltsov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

import curses
import argparse
from src import main, license
from src import is_git, no_git


def show_license() -> None:
    with open("LICENSE", "r") as f:
        return f.read().strip()

parser = argparse.ArgumentParser(prog="vigit")
parser.add_argument(
    "--license",
    action="store_true",
    help="show license and exit"
)

args = parser.parse_args()
result = is_git()
if not result[0]:
    curses.wrapper(lambda x: no_git(x, result[1]))
    exit(1)
elif args.license:
    text = show_license()
    func = lambda x: license(x, text)
    curses.wrapper(func)
    exit(0)
else:
    curses.wrapper(main)
    exit(0)
