#!/usr/bin/env python3

# vigit - Minimal TUI application for working with Git directly from the terminal.
# Copyright (C) 2026 vigit Pavel Shiltsov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

import curses
import argparse
from src import main, license


def show_license() -> None:
    with open("LICENSE", "r") as f:
        return f.read().strip()

parser = argparse.ArgumentParser(prog="vigit")
parser.add_argument(
    "--license",
    action="store_true",
    help="show license and exit"
)

args = parser.parse_args()

if args.license:
    text = show_license()
    func = lambda x: license(x, text)
    curses.wrapper(func)
    exit(0)
else:
    print("""vigit  Copyright (C) 2026
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see `vigit --license` for details.""")
    curses.wrapper(main)
    exit(0)
